# -*- coding: utf-8 -*-
"""
網頁介面測試(離線,不需網路與 Gemini API key,不會執行 main.py)
================================================================
用法:python tests/webapp_test.py

涵蓋:app.py 匯入隔離(不得連帶載入 main/fastf1)、output/ 掃描與狀態
判定(完成/失敗/未完成)、首頁渲染(場次表、SESSION_ALERT 橫幅)、
詳情頁(FB/IG 文案分段、配圖、summary/factcheck、FAILED 警示)、
檔案服務白名單與路徑跳脫防護、執行狀態 API(含執行中拒絕重複觸發)。

測試使用合成 fixtures(臨時目錄),不依賴機器上的真實 output/。
"""
import base64
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import app  # noqa: E402

# ---- 匯入隔離:app.py 不得 import main.py(避免其模組層副作用)----
assert 'main' not in sys.modules, 'app.py 不應 import main.py'
assert 'fastf1' not in sys.modules, 'app.py 不應載入 fastf1'

TMP = ROOT / 'tests' / '.tmp_webapp'
shutil.rmtree(TMP, ignore_errors=True)
PASSED = []


def check(name, cond, info=''):
    assert cond, f'[FAIL] {name} {info}'
    PASSED.append(name)


check('import isolation', True)

# ---- 合成 fixtures:完成 / 失敗 / 未完成 三種場次 ----
# 1x1 透明 PNG(最小合法圖檔)
PNG = base64.b64decode(
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJ'
    'AAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==')

POST = ('[generated by test-model @ 2026-01-01 00:00|已通過靜態檢查+數字查核+AI審核]\n\n'
        '=== FB版 ===\n測試 FB 文案內容\n#F1\n'
        '=== IG版 ===\n測試 IG 文案\n#F1')

out = TMP / 'output'
# 資料夾名稱帶大獎賽名稱尾綴(Round_01_Test_Grand_Prix,大寫開頭為現行格式);
# R/Q 同屬 round 1,驗證 app.py 的 session_dir/scan_output 能在有尾綴時
# 正確解析並共用同一資料夾
done_dir = out / '2026' / 'Round_01_Test_Grand_Prix' / 'R'
done_dir.mkdir(parents=True)
(done_dir / 'social_post.txt').write_text(POST, encoding='utf-8')
(done_dir / 'summary.txt').write_text(
    '2026 Test Grand Prix - Race (正賽)\n====\nP1 XX 92.451s', encoding='utf-8')
(done_dir / 'factcheck_report.txt').write_text('事實查核報告(測試)', encoding='utf-8')
(done_dir / 'chart_fastest_laps.png').write_bytes(PNG)
(done_dir / 'fastest_laps.csv').write_text('Driver\nXX', encoding='utf-8')

failed_dir = out / '2026' / 'Round_01_Test_Grand_Prix' / 'Q'
failed_dir.mkdir(parents=True)
(failed_dir / 'FAILED_gemini.txt').write_text('錯誤:測試用失敗標記', encoding='utf-8')
(failed_dir / 'summary.txt').write_text(
    '2026 Test Grand Prix - Qualifying (排位賽)', encoding='utf-8')

# round 2 故意用本功能上線前的舊格式(全小寫 round_02,無大獎賽名稱尾綴),
# 驗證新規則仍不分大小寫向下相容
pending_dir = out / '2026' / 'round_02' / 'SQ'
pending_dir.mkdir(parents=True)
(pending_dir / 'summary.txt').write_text(
    '2026 Next Grand Prix - Sprint Qualifying (衝刺排位)', encoding='utf-8')

(out / 'SESSION_ALERT.txt').write_text('測試警報內容', encoding='utf-8')

app.OUTPUT_DIR = out          # 指向 fixtures,不碰真實 output/
c = app.app.test_client()

# ---- 單元:split_post 拆段 ----
header, sections = app.split_post(POST)
check('split_post header', header.startswith('[generated by test-model'))
check('split_post sections', sections == [('FB', '測試 FB 文案內容\n#F1'),
                                          ('IG', '測試 IG 文案\n#F1')])

# ---- 掃描與狀態判定 ----
entries = {(e['year'], e['rnd'], e['code']): e for e in app.scan_output()}
check('scan count', len(entries) == 3)
check('scan status done', entries[(2026, 1, 'R')]['status'] == 'done')
check('scan status failed', entries[(2026, 1, 'Q')]['status'] == 'failed')
check('scan status pending', entries[(2026, 2, 'SQ')]['status'] == 'pending')
check('scan title', entries[(2026, 1, 'R')]['title'] == '2026 Test Grand Prix - Race (正賽)')

# ---- session_dir:有大獎賽名稱尾綴 / 無尾綴(舊格式) / 不存在的站次 ----
check('session_dir with slug', app.session_dir(2026, 1, 'R') == done_dir)
check('session_dir legacy no-slug', app.session_dir(2026, 2, 'SQ') == pending_dir)
check('session_dir missing round', app.session_dir(2026, 99, 'R') is None)

# ---- 首頁:場次表 + 警報橫幅 ----
html = c.get('/').get_data(as_text=True)
check('index rows', all(s in html for s in
                        ('/session/2026/1/R', '/session/2026/1/Q', '/session/2026/2/SQ')))
check('index badges', all(s in html for s in ('完成', '失敗', '未完成')))
check('index alert shown', 'SESSION_ALERT' in html and '測試警報內容' in html)
(out / 'SESSION_ALERT.txt').unlink()
check('index alert gone', '測試警報內容' not in c.get('/').get_data(as_text=True))

# ---- 詳情頁:完成場次 ----
html = c.get('/session/2026/1/R').get_data(as_text=True)
check('detail title', '2026 Test Grand Prix - Race (正賽)' in html)
check('detail fb/ig', 'FB 版' in html and 'IG 版' in html and '測試 FB 文案內容' in html)
check('detail copy data', 'data-text="測試 FB 文案內容' in html)
check('detail chart', '/files/2026/1/R/chart_fastest_laps.png' in html)
check('detail summary+factcheck', 'P1 XX 92.451s' in html and '事實查核報告(測試)' in html)
check('detail download', 'fastest_laps.csv' in html)

# ---- 詳情頁:失敗與未完成場次 ----
html = c.get('/session/2026/1/Q').get_data(as_text=True)
check('detail failed alert', 'FAILED_gemini.txt' in html and '測試用失敗標記' in html)
html = c.get('/session/2026/2/SQ').get_data(as_text=True)
check('detail pending no-post', '未完成' in html and 'FB 版' not in html)

# ---- 404 防護 ----
check('404 bad code', c.get('/session/2026/1/FP1').status_code == 404)
check('404 no dir', c.get('/session/2026/50/R').status_code == 404)
check('404 traversal', c.get(
    '/files/2026/1/R/..%2F..%2F..%2FGemini_API_Key.txt').status_code == 404)
check('404 bad ext', c.get('/files/2026/1/R/evil.exe').status_code == 404)
check('404 no file', c.get('/files/2026/1/R/chart_missing.png').status_code == 404)

# ---- 檔案服務:白名單內正常供檔 ----
# send_from_directory 的回應必須 close:Windows 上檔案 handle 未釋放,
# 結尾的 rmtree 會刪不掉暫存目錄(留下 .tmp_webapp 殘骸)
r = c.get('/files/2026/1/R/chart_fastest_laps.png')
check('serve png', r.status_code == 200 and r.data == PNG)
r.close()
r = c.get('/files/2026/1/R/fastest_laps.csv')
check('serve csv', r.status_code == 200)
r.close()

# ---- 執行狀態 API(不實際執行 main.py)----
d = c.get('/run/log').get_json()
check('runlog initial', d['running'] is False and d['returncode'] is None)
with app._run_lock:                      # 模擬執行中 → 重複觸發必須被拒
    app._run_state['running'] = True
try:
    check('run busy=409', c.post('/run').status_code == 409)
finally:
    with app._run_lock:
        app._run_state['running'] = False

# 清理不吞錯:若仍有檔案 handle 未釋放,這裡要直接失敗而不是留殘骸
shutil.rmtree(TMP)
check('cleanup complete', not TMP.exists())
print(f'\n全部通過:{len(PASSED)} 項檢查')
